"""
notes_to_tiles.py

Converts a list of (freq, duration) notes extracted from MIDI
into a tile JSON for the piano tiles game.

- t       = when the tile appears (seconds from start)
- row     = 0-5 based on frequency bucket
- width   = proportional to note duration (scaled to tile units)

Usage:
    python notes_to_tiles.py
    (edit the `notes` list at the bottom, output saved to tiles.json)
"""

import json
import math
import mido

mid = mido.MidiFile(r"C:\Users\bmdma\ledhack\3-Grame-De-haz\Matrix\songs\Pirates of the Caribbean - He's a Pirate (2).mid")

# ── Config ────────────────────────────────────────────────────────────────────
OUTPUT_FILE    = r"C:\Users\bmdma\ledhack\3-Grame-De-haz\Matrix\songs\song.json"
NUM_ROWS       = 6       # rows in the game (0–5)
MIN_WIDTH      = 2       # shortest tile width
MAX_WIDTH      = 8       # longest tile width
MIN_GAP        = 0.05    # minimum seconds of silence between tiles
                         # (set to 0 to let tiles touch end-to-end)
# ─────────────────────────────────────────────────────────────────────────────


def freq_to_row(freq, min_f, max_f):
    """Map a frequency to a row 0–5 using equal-width buckets."""
    if min_f == max_f:
        return 0
    bucket = (max_f - min_f) / NUM_ROWS
    row = int((freq - min_f) / bucket)
    return min(row, NUM_ROWS - 1)


def dur_to_width(dur, min_dur, max_dur):
    """Map a duration to a tile width between MIN_WIDTH and MAX_WIDTH."""
    if min_dur == max_dur:
        return MIN_WIDTH
    # linear scale
    ratio = (dur - min_dur) / (max_dur - min_dur)
    width = MIN_WIDTH + ratio * (MAX_WIDTH - MIN_WIDTH)
    return max(MIN_WIDTH, min(MAX_WIDTH, round(width)))


def notes_to_tiles(notes):
    """
    notes: list of (freq, duration_seconds)
    Returns a list of tile dicts.
    """
    freqs = [f for f, d in notes]
    durs  = [d for f, d in notes]

    min_f   = min(freqs)
    max_f   = max(freqs)
    min_dur = min(durs)
    max_dur = max(durs)

    tiles   = []
    cursor  = 0.0   # current time position in seconds

    for freq, dur in notes:
        t     = round(cursor, 3)
        row   = freq_to_row(freq, min_f, max_f)
        width = dur_to_width(dur, min_dur, max_dur)

        tiles.append({"t": t, "row": row, "width": width})

        # next tile starts right after this one ends (+ tiny gap)
        cursor += dur + MIN_GAP

    return tiles


def build_json(tiles):
    return {
        "format": 1,
        "comment": (
            "t = seconds from round start. "
            "row 0-5 mapped from frequency range (0=lowest, 5=highest). "
            "width proportional to note duration."
        ),
        "tiles": tiles,
    }


# ── Paste your notes list here ────────────────────────────────────────────────
# Format: list of (frequency_hz, duration_seconds)
# Generated by the MIDI extractor script.

tempo = 500000

NOTE_TO_FREQ = {n: round(440 * 2 ** ((n - 69) / 12)) for n in range(128)}

notes = []  # list of (freq, duration_in_seconds)
active = {}  # note -> start_time

elapsed = 0
for track in mid.tracks:
    elapsed = 0
    for msg in track:
        elapsed += mido.tick2second(msg.time, mid.ticks_per_beat, tempo)
        if msg.type == 'set_tempo':
            tempo = msg.tempo
        if msg.type == 'note_on' and msg.velocity > 0:
            active[msg.note] = elapsed
        if msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
            if msg.note in active:
                duration = elapsed - active.pop(msg.note)
                notes.append((NOTE_TO_FREQ[msg.note], round(duration, 3)))

print(notes)

fs = 44100
notes = notes[400:]  # limit to first 100 notes for testing``

if __name__ == "__main__":
    tiles  = notes_to_tiles(notes)
    result = build_json(tiles)

    with open(OUTPUT_FILE, "w") as f:
        json.dump(result, f, indent=2)

    print(f"Done — {len(tiles)} tiles saved to {OUTPUT_FILE}")
